version : '2'
services:
  mysql:
      image: mysql:latest
      ports: 
        -  3306:3306
      network_mode:  host
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: keepnote
        MYSQL_HOST: localhost
        MYSQL_USER: root
        MYSQL_PASSWORD: root

  mongo: 
      image: mongo:latest
      ports:
        - 27017:27017
      network_mode:  host
      environment: 
        MONGO_DATABASE: keepnote
        MONGO_PORT: 27017
        MONGO_HOST : localhost
    
  UserAuthService-app:
      image: userauthenticationservice
      build: server/UserAuthentication-Service
      restart: always
      network_mode: host
      depends_on: 
        - mysql
      ports:
        - 8081:8081
      expose:
        - 8081

  UserService-app:
      image: userservice
      build: server/UserService
      restart: always
      network_mode: host
      depends_on: 
        - mongo
      ports:
        - 8082:8082
      expose:
        - 8082  

  NoteService-app:
      image: noteservice
      build: server/NoteService
      restart: always
      network_mode: host
      depends_on: 
        - mongo
      ports:
        - 8083:8083
      expose:
        - 8083   

  CategoryService-app:
      image: categoryservice
      build: server/CategoryService
      restart: always
      network_mode: host
      depends_on: 
        - mongo
      ports:
        - 8084:8084
      expose:
        - 8084

  ReminderService-app:
      image: reminderservice
      build: server/ReminderService
      restart: always
      network_mode: host
      depends_on: 
        - mongo
      ports:
        - 8085:8085
      expose:
        - 8085    

  # keepnote-frontend:
  #     image : keepnote-frontend
  #     build: /
  #     network_mode: host
  #     ports:
  #       - 4200:8080
  #     expose : 
  #       -   8080                      
         